version: '3'

networks:
  app:
    driver: bridge

services:
  app:
    image: williamsuppo/php:1.0
    networks:
      - app
    volumes:
      - '.:/var/www'

  nginx:
    image: williamsuppo/nginx:1.0
    networks:
      - app
    volumes:
      - './public:/var/www/public'

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - app
