name: Run pipeline workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install composer dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Upload vendor
        uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: vendor
      - name: Build assets
        uses: actions/setup-node@v2
        with:
          node-version: '15'
        run: |
          npm install
          npm run prod
      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: public

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        run: php vendor/bin/phpunit
      - name: Download vendor
        uses: actions/download-artifact@v1
        with:
          name: vendor
          path: vendor
      - name: Download assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
