name: Run pipeline workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install composer dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute tests
        run: php vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Install composer dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Build assets
        run: |
          npm install
          npm run prod
      - name: Set env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env
      - name: Config ssh
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
